package Model.parser;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface  sym {
  /* terminals */
  public static final int FreeText = 4;
  public static final int Layer_Name = 16;
  public static final int BINARY = 26;
  public static final int Inputs = 5;
  public static final int Model_Type = 3;
  public static final int CloseBrace = 19;
  public static final int Comma = 23;
  public static final int Layer = 15;
  public static final int Input_Name = 7;
  public static final int Layers = 14;
  public static final int OpenPlaneBrace = 20;
  public static final int OpenBrace = 18;
  public static final int Output = 10;
  public static final int TwoPoints = 22;
  public static final int NUM = 27;
  public static final int Input_Type = 8;
  public static final int Model = 13;
  public static final int NUMBER = 24;
  public static final int Output_Name = 11;
  public static final int EOF = 0;
  public static final int Layer_Params = 17;
  public static final int CATEGORICAL = 25;
  public static final int error = 1;
  public static final int ClosePlaneBrace = 21;
  public static final int Input = 6;
  public static final int Output_Type = 12;
  public static final int Outputs = 9;
  public static final int Model_Name = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Model_Name",
  "Model_Type",
  "FreeText",
  "Inputs",
  "Input",
  "Input_Name",
  "Input_Type",
  "Outputs",
  "Output",
  "Output_Name",
  "Output_Type",
  "Model",
  "Layers",
  "Layer",
  "Layer_Name",
  "Layer_Params",
  "OpenBrace",
  "CloseBrace",
  "OpenPlaneBrace",
  "ClosePlaneBrace",
  "TwoPoints",
  "Comma",
  "NUMBER",
  "CATEGORICAL",
  "BINARY",
  "NUM"
  };
}

